name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Linux:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: npm install
    - name: Node JS CI
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
    - run: npm ci
    - name: Build React
      run: CI=false npm run build
    - name: Wine 
      run: |
        sudo dpkg --add-architecture i386
        wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        sudo apt install --install-recommends winehq-stable
    - name: Build Electron
      run: npm run build-electron-cl
    - name: Upload to Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts (Linux/FreeBSD)
        path: |
          dist/*.deb
          dist/*.snap
          dist/*.freebsd
          dist/*.AppImage
        
  macOS:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: npm install
    - name: Node JS CI
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
    - run: npm ci
    - name: Build React
      run: CI=false npm run build
    - name: Build Electron
      run: npm run build-electron-mac-cl
    - name: Upload to Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts (macOS)
        path: dist/*.dmg
        
  Windows:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: npm install
    - name: Node JS CI
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
    - run: npm ci
    - name: Build React
      run: $env:CI=$false; npm run build
    - name: Build Electron
      run: npm run build-electron-cl
    - name: Upload to Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts (Windows)
        path: dist/*.exe
